package com.xr.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import vendingmachine.xr.com.coffeemachine.pojo.AD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AD".
*/
public class ADDao extends AbstractDao<AD, Long> {

    public static final String TABLENAME = "AD";

    /**
     * Properties of entity AD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AdVideo = new Property(1, String.class, "adVideo", false, "AD_VIDEO");
        public final static Property AdPictire = new Property(2, String.class, "adPictire", false, "AD_PICTIRE");
    }


    public ADDao(DaoConfig config) {
        super(config);
    }
    
    public ADDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"AD_VIDEO\" TEXT," + // 1: adVideo
                "\"AD_PICTIRE\" TEXT);"); // 2: adPictire
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String adVideo = entity.getAdVideo();
        if (adVideo != null) {
            stmt.bindString(2, adVideo);
        }
 
        String adPictire = entity.getAdPictire();
        if (adPictire != null) {
            stmt.bindString(3, adPictire);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String adVideo = entity.getAdVideo();
        if (adVideo != null) {
            stmt.bindString(2, adVideo);
        }
 
        String adPictire = entity.getAdPictire();
        if (adPictire != null) {
            stmt.bindString(3, adPictire);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AD readEntity(Cursor cursor, int offset) {
        AD entity = new AD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // adVideo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // adPictire
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAdVideo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAdPictire(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AD entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
