package com.xr.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import vendingmachine.xr.com.coffeemachine.pojo.AD;
import vendingmachine.xr.com.coffeemachine.pojo.goods;
import vendingmachine.xr.com.coffeemachine.pojo.Order;
import vendingmachine.xr.com.coffeemachine.pojo.SaleGoods;

import com.xr.database.dao.ADDao;
import com.xr.database.dao.goodsDao;
import com.xr.database.dao.OrderDao;
import com.xr.database.dao.SaleGoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aDDaoConfig;
    private final DaoConfig goodsDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig saleGoodsDaoConfig;

    private final ADDao aDDao;
    private final goodsDao goodsDao;
    private final OrderDao orderDao;
    private final SaleGoodsDao saleGoodsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aDDaoConfig = daoConfigMap.get(ADDao.class).clone();
        aDDaoConfig.initIdentityScope(type);

        goodsDaoConfig = daoConfigMap.get(goodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        saleGoodsDaoConfig = daoConfigMap.get(SaleGoodsDao.class).clone();
        saleGoodsDaoConfig.initIdentityScope(type);

        aDDao = new ADDao(aDDaoConfig, this);
        goodsDao = new goodsDao(goodsDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        saleGoodsDao = new SaleGoodsDao(saleGoodsDaoConfig, this);

        registerDao(AD.class, aDDao);
        registerDao(goods.class, goodsDao);
        registerDao(Order.class, orderDao);
        registerDao(SaleGoods.class, saleGoodsDao);
    }
    
    public void clear() {
        aDDaoConfig.clearIdentityScope();
        goodsDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        saleGoodsDaoConfig.clearIdentityScope();
    }

    public ADDao getADDao() {
        return aDDao;
    }

    public goodsDao getGoodsDao() {
        return goodsDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public SaleGoodsDao getSaleGoodsDao() {
        return saleGoodsDao;
    }

}
