package com.xr.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import vendingmachine.xr.com.coffeemachine.pojo.Order;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER".
*/
public class OrderDao extends AbstractDao<Order, Void> {

    public static final String TABLENAME = "ORDER";

    /**
     * Properties of entity Order.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property OrderNo = new Property(0, String.class, "orderNo", false, "ORDER_NO");
        public final static Property AliCode = new Property(1, String.class, "aliCode", false, "ALI_CODE");
        public final static Property WxCode = new Property(2, String.class, "wxCode", false, "WX_CODE");
        public final static Property Result = new Property(3, int.class, "result", false, "RESULT");
    }


    public OrderDao(DaoConfig config) {
        super(config);
    }
    
    public OrderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER\" (" + //
                "\"ORDER_NO\" TEXT," + // 0: orderNo
                "\"ALI_CODE\" TEXT," + // 1: aliCode
                "\"WX_CODE\" TEXT," + // 2: wxCode
                "\"RESULT\" INTEGER NOT NULL );"); // 3: result
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Order entity) {
        stmt.clearBindings();
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(1, orderNo);
        }
 
        String aliCode = entity.getAliCode();
        if (aliCode != null) {
            stmt.bindString(2, aliCode);
        }
 
        String wxCode = entity.getWxCode();
        if (wxCode != null) {
            stmt.bindString(3, wxCode);
        }
        stmt.bindLong(4, entity.getResult());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Order entity) {
        stmt.clearBindings();
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(1, orderNo);
        }
 
        String aliCode = entity.getAliCode();
        if (aliCode != null) {
            stmt.bindString(2, aliCode);
        }
 
        String wxCode = entity.getWxCode();
        if (wxCode != null) {
            stmt.bindString(3, wxCode);
        }
        stmt.bindLong(4, entity.getResult());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Order readEntity(Cursor cursor, int offset) {
        Order entity = new Order( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // orderNo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // aliCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // wxCode
            cursor.getInt(offset + 3) // result
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Order entity, int offset) {
        entity.setOrderNo(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAliCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWxCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setResult(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Order entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Order entity) {
        return null;
    }

    @Override
    public boolean hasKey(Order entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
